name: MAUI CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Build
      run: dotnet publish DeepWorkTracker.csproj -f net9.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=mauiboilerplate.keystore -p:AndroidSigningKeyAlias=mauiboilerplate-keystore -p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}"
    - name: List build output
      run: ls -R bin/Release/net9.0-android/publish/
    - uses: r0adkll/upload-google-play@v1.1.3
      name: Upload Android Artifact to Play Console
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
        packageName: com.maxmannstein.mauiboilerplate
        releaseFiles: bin/Release/net9.0-android/publish/com.maxmannstein.mauiboilerplate-Signed.aab
        track: internal
        status: draft
  build-ios:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-filepath: 'AppleSigningCertificate.p12'
        p12-password: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.maxmannstein.mauiboilerplate'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: Build
      run: dotnet publish DeepWorkTracker.csproj -f net9.0-ios -c Release -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false
    - name: List build output
      run: ls -R bin/Release/net9.0-ios/publish/
    - name: Upload app to TestFlight
      uses: Apple-Actions/upload-testflight-build@v1
      with:
        app-path: 'bin/Release/net9.0-ios/publish/DeepWorkTracker.ipa'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
